###  Register new user
POST  http://localhost:5000/api/users/auth/register
Content-Type: application/json

{
    "email": "test2@gmail.com",
    "password": "123456789",
    "username": "khalil" 
}

###  Login
POST  http://localhost:5000/api/users/auth/login
Content-Type: application/json

{
    "email": "test1@gmail.com",
    "password": "123456789"
}

### get current user
GET  http://localhost:5000/api/users/current-user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlclR5cGUiOiJhZG1pbiIsImlhdCI6MTczMzA2MzEzNCwiZXhwIjoxNzMzMTQ5NTM0fQ.T9VHPN0VgyOmBg_qFgasrI407lkiSX1osdTlBKLvH-Q


### get all users with admin user
GET  http://localhost:5000/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlclR5cGUiOiJhZG1pbiIsImlhdCI6MTczMzA2MzEzNCwiZXhwIjoxNzMzMTQ5NTM0fQ.T9VHPN0VgyOmBg_qFgasrI407lkiSX1osdTlBKLvH-Q

### get all users with Normal user
GET  http://localhost:5000/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlclR5cGUiOiJub3JtYWxfdXNlciIsImlhdCI6MTczMTgzNjg2MiwiZXhwIjoxNzU3NzU2ODYyfQ.J4Cy5F7BKsHlhANZULqWGcd6ZEtVnl0VGgn4dagQQKU


### update user
PUT  http://localhost:5000/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlclR5cGUiOiJub3JtYWxfdXNlciIsImlhdCI6MTczMjM2NzM3MSwiZXhwIjoxNzU4Mjg3MzcxfQ.nRhqicG0KyFDA_Q8vqwsEKTFx-qQeCwfCMqdVphfi7M

{
    "username": "khalil2update",
    "password": "123456789"
}

### delete user 
DELETE  http://localhost:5000/api/users/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlclR5cGUiOiJub3JtYWxfdXNlciIsImlhdCI6MTczMTgzNjg2MiwiZXhwIjoxNzU3NzU2ODYyfQ.J4Cy5F7BKsHlhANZULqWGcd6ZEtVnl0VGgn4dagQQKU

